---
- name: restart service apache2
  service:
    name: apache2
    state: started
  register: app_stat
  when: ansible_distribution == "Ubuntu"
  
- name: restart service httpd
  service:
    name: httpd
    state: started
  register: app_stat
  when: ansible_distribution == "Redhat"
  
- debug: msg="{{ ansible_distribution }} Restarted"
  tags: restart_apache2
